// Campaign metrics data
export const campaignMetrics = {
  budget: 50000,
  spent: 32500,
  impressions: {
    value: 750000,
    change: 12.5,
  },
  engagement: {
    value: "2.3%",
    change: 8.7,
  },
  trend: {
    value: "+15%",
    change: 5.2,
  },
  status: "Live",
};

// Top creator profile data
export const topCreatorData = {
  id: "creator-001",
  name: "Sarah Johnson",
  image: "https://randomuser.me/api/portraits/women/44.jpg",
  profilePicture: "https://randomuser.me/api/portraits/women/44.jpg",
  category: "Lifestyle & Fashion Influencer",
  linkedInId: "sarahjohnson",
  country: "United States",
  jobTitle: "Content Creator",
  company: "Self-Employed",
  followers: 125000,
  status: "Approved",
  ongoingSpend: 5000,
  paymentStatus: "paid",
  impressions: 750000,
  engagement: 4.8,
  averageImpressions: 120000,
  averageEngagement: 4.5,
  submissionDate: "2023-05-15",
  contentStatus: "published",
  postsCompleted: 8,
  totalPosts: 10,
  stats: {
    followers: 125000,
    weeklyGrowth: 2.7,
    engagement: 4.8,
    performance: {
      current: 92,
      change: "+5%",
    },
  },
  posts: [
    {
      numberstatus: 6,
      id: "post-001",
      title: "Product Review",
      date: "2023-06-01",
      status: "published",
      content: "Sharing my honest review of this amazing product!",
      impressions: 125000,
      engagement: 4.8,
      link: "https://linkedin.com/post/12345",
      contentItems: [
        {
          id: "content-001",
          type: "image",
          content: "Product showcase with lifestyle setting",
          date: "2023-06-01",
          status: "published",
          images: [
            "https://example.com/image1.jpg",
            "https://example.com/image2.jpg",
          ],
        },
      ],
    },
  ],
};

// Engagement trend data
export const engagementData = [
  { date: "Week 1", impressions: 120000, engagement: 3600 },
  { date: "Week 2", impressions: 140000, engagement: 4200 },
  { date: "Week 3", impressions: 135000, engagement: 4050 },
  { date: "Week 4", impressions: 180000, engagement: 5400 },
  { date: "Week 5", impressions: 165000, engagement: 4950 },
  { date: "Week 6", impressions: 195000, engagement: 5850 },
];

// Creator performance radar chart data
export const creatorPerformanceData = [
  { subject: "Engagement", A: 120, B: 110 },
  { subject: "Reach", A: 98, B: 130 },
  { subject: "Consistency", A: 86, B: 130 },
  { subject: "Content Quality", A: 99, B: 100 },
  { subject: "Audience Match", A: 85, B: 90 },
  { subject: "Growth Rate", A: 65, B: 85 },
];

// All creators table data
export const allCreatorsData = [
  {
    id: "creator-001",
    name: "Sarah Johnson",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    profilePicture: "https://randomuser.me/api/portraits/women/44.jpg",
    linkedInId: "sarahjohnson",
    country: "United States",
    jobTitle: "Content Creator",
    company: "Self-Employed",
    followers: 125000,
    status: "Approved",
    ongoingSpend: 5000,
    paymentStatus: "paid",
    impressions: 125000,
    engagement: 4.8,
    averageImpressions: 120000,
    averageEngagement: 4.5,
    submissionDate: "2023-05-15",
    contentStatus: "published",
    postsCompleted: 8,
    totalPosts: 10,
    lastPost: "Instagram Post",
    engRate: "4.8%",
    reactions: 8750,
    comments: 420,
    trend: "+12%",
  },
  {
    id: "creator-002",
    name: "Michael Chen",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    profilePicture: "https://randomuser.me/api/portraits/men/32.jpg",
    linkedInId: "michaelchen",
    country: "Canada",
    jobTitle: "Digital Marketing Specialist",
    company: "Tech Solutions Inc.",
    followers: 98000,
    status: "Approved",
    ongoingSpend: 4200,
    paymentStatus: "in_process",
    impressions: 98000,
    engagement: 5.2,
    averageImpressions: 95000,
    averageEngagement: 5.0,
    submissionDate: "2023-05-18",
    contentStatus: "published",
    postsCompleted: 6,
    totalPosts: 8,
    lastPost: "TikTok Video",
    engRate: "5.2%",
    reactions: 6500,
    comments: 380,
    trend: "+8%",
  },
  {
    id: "creator-003",
    name: "Jessica Williams",
    avatar: "https://randomuser.me/api/portraits/women/63.jpg",
    profilePicture: "https://randomuser.me/api/portraits/women/63.jpg",
    linkedInId: "jessicawilliams",
    country: "United Kingdom",
    jobTitle: "Content Strategist",
    company: "Creative Media Ltd",
    followers: 75000,
    status: "Approved",
    ongoingSpend: 3800,
    paymentStatus: "paid",
    impressions: 75000,
    engagement: 3.9,
    averageImpressions: 72000,
    averageEngagement: 3.8,
    submissionDate: "2023-05-20",
    contentStatus: "published",
    postsCompleted: 5,
    totalPosts: 7,
    lastPost: "YouTube Video",
    engRate: "3.9%",
    reactions: 4200,
    comments: 310,
    trend: "+5%",
  },
  {
    id: "creator-004",
    name: "David Rodriguez",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    profilePicture: "https://randomuser.me/api/portraits/men/75.jpg",
    linkedInId: "davidrodriguez",
    country: "Spain",
    jobTitle: "Social Media Manager",
    company: "Global Brands",
    followers: 62000,
    status: "Approved",
    ongoingSpend: 3200,
    paymentStatus: "unpaid",
    impressions: 62000,
    engagement: 4.1,
    averageImpressions: 60000,
    averageEngagement: 4.0,
    submissionDate: "2023-05-22",
    contentStatus: "published",
    postsCompleted: 4,
    totalPosts: 6,
    lastPost: "Instagram Story",
    engRate: "4.1%",
    reactions: 3800,
    comments: 245,
    trend: "+7%",
  },
  {
    id: "creator-005",
    name: "Emma Thompson",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    profilePicture: "https://randomuser.me/api/portraits/women/33.jpg",
    linkedInId: "emmathompson",
    country: "Australia",
    jobTitle: "Brand Ambassador",
    company: "Lifestyle Brands Co.",
    followers: 45000,
    status: "Approved",
    ongoingSpend: 2500,
    paymentStatus: "paid",
    impressions: 45000,
    engagement: 3.5,
    averageImpressions: 42000,
    averageEngagement: 3.3,
    submissionDate: "2023-05-25",
    contentStatus: "published",
    postsCompleted: 3,
    totalPosts: 5,
    lastPost: "LinkedIn Post",
    engRate: "3.5%",
    reactions: 2900,
    comments: 185,
    trend: "+4%",
  },
];

export const campaignsData = [
  {
    id: 1,
    name: "Q1 Product Launch",
    status: "Active",
    budget: 45000,
    spent: 14086,
    impressions: 490052,
    engagement: "1.8%",
    trend: "+12%",
    startDate: "2024-01-01",
    endDate: "2024-03-31",
  },
  {
    id: 2,
    name: "Brand Awareness Campaign",
    status: "Active",
    budget: 35000,
    spent: 28500,
    impressions: 385000,
    engagement: "2.1%",
    trend: "+8%",
    startDate: "2024-02-01",
    endDate: "2024-04-30",
  },
  {
    id: 3,
    name: "Summer Sale Promotion",
    status: "Scheduled",
    budget: 25000,
    spent: 0,
    impressions: 0,
    engagement: "0%",
    trend: "0%",
    startDate: "2024-06-01",
    endDate: "2024-08-31",
  },
];

export const performanceData = [
  { month: "Jan", impressions: 400000, engagement: 8500 },
  { month: "Feb", impressions: 600000, engagement: 12000 },
  { month: "Mar", impressions: 550000, engagement: 11000 },
  { month: "Apr", impressions: 780000, engagement: 15600 },
  { month: "May", impressions: 650000, engagement: 13000 },
  { month: "Jun", impressions: 850000, engagement: 17000 },
];
